/* Auto-generated.  Manually edit as needed */
#include "v120_common.h"
const char *v120_help_string =
"v120 - miscellaneous utilities for the V120.\n"
"\n"
"SYNOPSIS\n"
"       v120  [-efFv]  [-a  awidth]  [-d  dwidth]  [-m crate_no] [-s speed] [-S\n"
"       slot0] subcommand [args]\n"
"\n"
"       v120 flash-upgrade upgrade_file\n"
"       v120 reset\n"
"       v120 write address [value[...]]\n"
"       v120 read address [count]\n"
"       v120 sysreset\n"
"       v120 loopback-upgrade upgrade_file\n"
"       v120 requester [bus]\n"
"       v120 scan\n"
"       v120 persist\n"
"\n"
"       v120 report flash|id|ident|power|uptime|status|pci|pcie\n"
"       v120 report monitor [monitor]\n"
"\n"
"OPTIONS\n"
"       -m crate, --crate_no=crate\n"
"           Specify  the  crate  number.  crate is 0 to 15, or A to perform the\n"
"           command on all crates.  If this option is not used, then the target\n"
"           will  be  the  lowest-number  connected  crate.  The flash-upgrade,\n"
"           loopback-upgrade, reset, and sysreset subcommands require the crate\n"
"           to be specified. They do not permit -m A. The report pci subcommand\n"
"           also does not support -m A.\n"
"\n"
"       -a awidth, --awidth=awidth\n"
"       -d dwidth, --dwidth=dwidth\n"
"       -s speed, --speed=speed\n"
"           For v120 read and v120 write, set the address modifier, data width,\n"
"           and  speed  of the VME transaction. awidth is one of 16, 24, or 32.\n"
"           dwidth is one of: b for 8 bits, w for 16 bits, l for 32 bits, and s\n"
"           for  32 bits split into two D16 transactions. speed is 0 to 3, with\n"
"           0 being the slowest and 3 being the fastest.\n"
"\n"
"           For v120 scan, if -a24 is used, then the A24 address space will  be\n"
"           scanned  *in addition to* the A16 address space.  The other address\n"
"           modifiers, data width and speed options are ignored.\n"
"\n"
"       -b --binary\n"
"           For v120 read and v120 write,  if using standard in/out instead  of\n"
"           command-line values, print or accept binary data instead of  string\n"
"           expressions\n"
"\n"
"       -e, --vmeprint\n"
"           For the read and write subcommands, print some debugging info about\n"
"           the VME transaction to standard error.\n"
"\n"
"       -f, --fpga\n"
"           For the reset subcommand, only reset the FPGA registers.\n"
"\n"
"       -F, --fair\n"
"           For  the requester subcommand, set bus to \"fair\".  The bus argument\n"
"           must be included.\n"
"\n"
"       -S slot0, --slot0=slot0\n"
"           For the requester subcommand, assert whether  the  V120  is  system\n"
"           controller  or not.  If slot0 is one of \"1yYtT\", the V120 is set as\n"
"           the system controller.  If slot0 is on of \"0nNfF\", the V120  is  no\n"
"           longer  the  system  controller.  If the option is unused, then the\n"
"           system controller status will remain  unchanged.   This  option  is\n"
"           independent of whether you use the requester subcommand as a set or\n"
"           a query.\n"
"\n"
"       -v, --verbose\n"
"           Reserved, in case we wish to add a verbose-mode option.\n"
"\n"
"       -V, --version\n"
"       -?, --help\n"
"           Show version/help\n"
"SEE ALSO\n"
"       v120 (1), v120(7)\n"
"";
